"""Generate JSON and Markdown run reports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

from models import CoverageSummary, ExecutionResult, FailureRecord, RunSummary, to_serializable
from utils import ensure_dir


class ReportGenerator:
    """Persist structured run reports in JSON and Markdown."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        ensure_dir(self.output_dir)

    def write_reports(
        self,
        run_summary: RunSummary,
        coverage: CoverageSummary,
        failure_counts: Dict[str, int],
        failures: List[FailureRecord],
        execution_results: List[ExecutionResult],
    ) -> Dict[str, Path]:
        """Write both JSON and Markdown reports and return paths."""
        json_path = self.output_dir / "report.json"
        md_path = self.output_dir / "report.md"
        payload = {
            "summary": to_serializable(run_summary),
            "coverage_summary": to_serializable(coverage),
            "execution_results": to_serializable(execution_results),
            "failure_analysis_summary": {
                "counts_per_failure_category": failure_counts,
                "failures": to_serializable(failures),
            },
        }
        json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=True), encoding="utf-8")
        md_path.write_text(
            self._build_markdown(run_summary, coverage, failure_counts, failures, execution_results),
            encoding="utf-8",
        )
        return {"json_report": json_path, "markdown_report": md_path}

    def _build_markdown(
        self,
        run_summary: RunSummary,
        coverage: CoverageSummary,
        failure_counts: Dict[str, int],
        failures: List[FailureRecord],
        execution_results: List[ExecutionResult],
    ) -> str:
        lines: List[str] = []
        lines.append("# Failure-Aware OpenAPI Tester Report")
        lines.append("")
        lines.append("## Summary")
        lines.append(f"- Spec name: `{run_summary.spec_name}`")
        lines.append(f"- Total operations parsed: `{run_summary.total_operations_parsed}`")
        lines.append(f"- Total operations selected: `{run_summary.total_operations_selected}`")
        lines.append(f"- Total tests generated: `{run_summary.total_tests_generated}`")
        lines.append(f"- Tests executed: `{run_summary.tests_executed}`")
        lines.append(f"- Passed: `{run_summary.passed}`")
        lines.append(f"- Failed: `{run_summary.failed}`")
        lines.append(f"- Execution errors: `{run_summary.execution_errors}`")
        lines.append("")
        lines.append("## Coverage Summary")
        lines.append(f"- Resource groups found: `{', '.join(coverage.resource_groups_found) or 'none'}`")
        lines.append(f"- Resource groups covered: `{', '.join(coverage.resource_groups_covered) or 'none'}`")
        lines.append(
            "- Behavioral partitions covered: "
            f"`{', '.join(coverage.behavioral_partitions_covered) or 'none'}`"
        )
        lines.append(f"- Selected operations: `{', '.join(coverage.selected_operations) or 'none'}`")
        lines.append("")
        lines.append("## Failure Analysis Summary")
        if failure_counts:
            for category, count in sorted(failure_counts.items(), key=lambda item: item[0]):
                lines.append(f"- `{category}`: `{count}`")
        else:
            lines.append("- No failures detected.")
        lines.append("")
        lines.append("## Per-Test Execution Results")
        if not execution_results:
            lines.append("No executed tests recorded.")
        else:
            for exec_result in execution_results:
                case = exec_result.test_case
                status = "PASSED" if exec_result.passed else "FAILED"
                lines.append(f"### {case.test_id} ({status})")
                lines.append(f"- Operation: `{case.operation_id}`")
                lines.append(f"- Endpoint: `{exec_result.endpoint}`")
                lines.append(f"- Method: `{case.method.upper()}`")
                lines.append(f"- Test type: `{case.test_type}`")
                lines.append(f"- Generated by: `{case.generated_by}`")
                lines.append(f"- Expected statuses: `{case.expected_statuses}`")
                lines.append(f"- Observed status: `{exec_result.observed_status}`")
                if exec_result.error:
                    lines.append(f"- Execution error: {exec_result.error}")
                if case.expected_response_summary:
                    lines.append(f"- Expected response intent: {case.expected_response_summary}")
                lines.append("")

        lines.append("")
        lines.append("## Per-Test Failure Details")
        if not failures:
            lines.append("No failing tests.")
            return "\n".join(lines)

        for item in failures:
            exec_result = item.execution
            case = exec_result.test_case
            lines.append(f"### {case.test_id}")
            lines.append(f"- Operation: `{case.operation_id}`")
            lines.append(f"- Endpoint: `{exec_result.endpoint}`")
            lines.append(f"- Method: `{case.method.upper()}`")
            lines.append(f"- Test type: `{case.test_type}`")
            lines.append(f"- Generated by: `{case.generated_by}`")
            if case.expected_response_summary:
                lines.append(f"- Expected response intent: {case.expected_response_summary}")
            lines.append(f"- Expected statuses: `{case.expected_statuses}`")
            lines.append(f"- Observed status: `{exec_result.observed_status}`")
            lines.append(
                f"- Heuristic classification: `{item.heuristic.category}` "
                f"(confidence `{item.heuristic.confidence}`)"
            )
            lines.append(f"- Heuristic reason: {item.heuristic.reason}")
            if item.llm:
                lines.append(f"- LLM likely cause: {item.llm.likely_cause}")
                lines.append(f"- LLM QA bug summary: {item.llm.qa_bug_summary}")
                follow_ups = item.llm.suggested_follow_up_tests or []
                lines.append("- Suggested follow-up tests:")
                for entry in follow_ups:
                    lines.append(f"  - {entry}")
            lines.append("")
        return "\n".join(lines)
